# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='exam_aids_code',
            new_name='exam_support_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='exam_aids_name',
            new_name='exam_support_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='ects_credits',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_previous_knowledge',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='required_previous_knowledge',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
