# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170220_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.DateField(null=True),
        ),
    ]
